version: '2'

services:
  awesome-convert:
    image: awesome-convert
    container_name: awesome-convert-test-server
    command: yarn test:all
    environment:
      NODE_ENV: development
      SERVER_URL: localhost
    build:
      context: .
      dockerfile: ./.docker/node.dev.dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3000:4000"
    tty: true
